[package]
name = "bc_constructor"
version = "0.1.0"
edition = "2024"

[dependencies]
bc_utils_lg = {path = "../bc_utils_lg"}
bc_indicators = {path = "../bc_indicators"}
bc_exch_api_funcs = {path = "../bc_exch_api_funcs"}
bc_utils = {path = "../bc_utils"}
bc_signals = {path = "../bc_signals"}

bc_pack_indicators = {path = "../bc_pack_indicators"}
bc_pack_signals_ready = {path = "../bc_pack_signals_ready"}
bc_pack_signals_train = {path = "../bc_pack_signals_train"} 

rustc-hash = "1.1"
serde ={ version = "1.0", features = ["derive"]}
serde_json5 = "0.1"
indexmap = {version = "2.0", features=["serde"]}
num-traits = "0.2.19"
clap = {version="4.6.1", features=["derive"]}
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
criterion = {version ="0.3.5", features = ["html_reports"]}

[[bench]]
name = "indicators"
harness = false
path = "benches/indicators.rs"

[[bench]]
name = "signals_ready"
harness = false
path = "benches/signals_ready.rs"

[[bench]]
name = "signals_train"
harness = false
path = "benches/signals_train.rs"