[package]
name = "bc_symbol_filters_gw"
version = "0.1.0"
edition = "2024"

[dependencies]
bc_utils_lg = {path = "../bc_utils_lg"}
bc_utils = {path = "../bc_utils"}
bc_symbol_filters = {path = "../bc_symbol_filters"}

[dev-dependencies]
bc_test_kit = {path = "../bc_test_kit"}
bc_packs = {path = "../bc_packs"}

pretty_assertions = "1"
criterion = {version = "0.8", features = ["html_reports"]}